# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-31 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20210131_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='neighbourhood',
            new_name='neighborhood',
        ),
    ]
