# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-31 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20210131_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='image',
            new_name='hood_image',
        ),
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='name',
            new_name='hood_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='neighbourhoods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hood.Neighbourhood'),
        ),
    ]
