# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-31 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_auto_20210131_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='population',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='health_tell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
