# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-31 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_auto_20210131_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='occupants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
