# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-01 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0007_neighbourhood_occupants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='occupants',
        ),
    ]
