# Generated by Django 3.1.5 on 2021-02-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0009_auto_20210201_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to='profile_pic'),
        ),
    ]
