# Generated by Django 3.1.5 on 2021-02-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0010_auto_20210201_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='', upload_to='profile_pic'),
        ),
    ]
